### PR TITLE
structure: else, elseif, break

### PR DESCRIPTION
**Pull request by wickedOne**
Do not use else, elseif, break after if and case conditions which return or throw something

recorded in #66 

yeah i know, it's ugly... 😎

### CODE REVIEW

**Comment by djoos** [comment]
Thanks for your contribution @wickedOne!

**Comment by VincentLanglet** [comment]
@djoos @wickedOne The following code return an error:

if ('c' === $dummy) {

$function = function () { return null; };

} elseif ('d' === $dummy) { return null; }

**Comment by wickedOne** [comment]
@VincentLanglet thanks for reporting!
i ran into that one myself last week so the fix is waiting over here: https://github.com/djoos/Symfony-coding-standard/pull/90

if you urgently need this patch, take [the code from the pull request](https://raw.githubusercontent.com/wickedOne/Symfony2-coding-standard/7a4b1f31ebcf82d687f3e8b0a3b20044999de0c9/Symfony/Sniffs/Formatting/ReturnOrThrowSniff.php) for the time being. 
quite sure @djoos will test and merge it in the next couple of days

**Comment by VincentLanglet** [comment]
@wickedOne Thanks ! Didn't see the PR

**Pull request merged**
